#!/usr/bin/env bash

set -ex

cd "$(dirname "$0")" || exit 1

(cd jekyll && nix develop -L --command bash -c "jekyll build --lsi")
rm -rf docs/
rsync -av --exclude .git --delete ./archive/ docs/
mkdir docs/archive/
mv docs/index.html docs/archive/
rsync -av --exclude .git ./jekyll/_site/ docs/

rsync -av --delete docs/ ~/g/vyxos/sites/kivikakk.ee/
