#!/bin/bash

set -ex

cd "$(dirname "$0")" || exit 1

(cd jekyll && jekyll build --lsi)
rsync -avz --exclude .git --delete ./jekyll/_site/ www@sylph.mesh.arrakis.hrzn.ee:~/public/kivikakk/
rsync -avz --exclude .git --delete ./archive/ www@sylph.mesh.arrakis.hrzn.ee:~/public/kivikakk/archive/
