title: kivikakk.ee
url: https://kivikakk.ee
paginate: 5
paginate_path: "/posts/:num/"
baseurl: ""
permalink: pretty
excerpt_separator: <!--more-->

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - THEME-LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Asherah Connor
  url: https://kivikakk.ee
  email: ashe@kivikakk.ee

version: 3.0.0

nav:
  - title: Home
    url: /

  - title: "About"
    url: /about/

  - title: "Index"
    url: /index/
