# Setup
title: kivikakk.ee
url: https://kivikakk.ee
paginate: 5
paginate_path: "/posts/:num/"
baseurl: ""
permalink: pretty
excerpt_separator: <!--more-->

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - THEME-LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Asherah Connor
  url: https://kivikakk.ee
  email: ashe@kivikakk.ee

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Home
    url: /

  - title: "About"
    url: "/about"

  - title: "GitHub"
    url: "https://github.com/kivikakk"

  - title: "Forge"
    url: "https://hrzn.ee/kivikakk"

  - title: "Index"
    url: /index
